Import library yang akan digunakan untuk memproses data

In [57]:
import numpy as np
import pandas as pd

Membaca data dari file csv dan menampilkan ringkasan dari data

In [58]:
books = pd.read_csv('/content/goodreads_data.csv')
books

,Unnamed: 0,Book,Author,Description,Genres,Avg_Rating,Num_Ratings,URL
0,0,To Kill a Mockingbird,Harper Lee,The unforgettable novel of a childhood in a sl...,"['Classics', 'Fiction', 'Historical Fiction', ...",4.27,"5,691,311",https://www.goodreads.com/book/show/2657.To_Ki...
1,1,Harry Potter and the Philosopher’s Stone (Harr...,J.K. Rowling,Harry Potter thinks he is an ordinary boy - un...,"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4.47,"9,278,135",https://www.goodreads.com/book/show/72193.Harr...
2,2,Pride and Prejudice,Jane Austen,"Since its immediate success in 1813, Pride and...","['Classics', 'Fiction', 'Romance', 'Historical...",4.28,"3,944,155",https://www.goodreads.com/book/show/1885.Pride...
3,3,The Diary of a Young Girl,Anne Frank,Discovered in the attic in which she spent the...,"['Classics', 'Nonfiction', 'History', 'Biograp...",4.18,"3,488,438",https://www.goodreads.com/book/show/48855.The_...
4,4,Animal Farm,George Orwell,Librarian's note: There is an Alternate Cover ...,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",3.98,"3,575,172",https://www.goodreads.com/book/show/170448.Ani...
...,...,...,...,...,...,...,...,...
9995,9995,"Breeders (Breeders Trilogy, #1)",Ashley Quigley,How far would you go? If human society was gen...,"['Dystopia', 'Science Fiction', 'Post Apocalyp...",3.44,276,https://www.goodreads.com/book/show/22085400-b...
9996,9996,Dynamo,Eleanor Gustafson,Jeth Cavanaugh is searching for a new life alo...,[],4.23,60,https://www.goodreads.com/book/show/20862902-d...
9997,9997,The Republic of Trees,Sam Taylor,This dark fable tells the story of four Englis...,"['Fiction', 'Horror', 'Dystopia', 'Coming Of A...",3.29,383,https://www.goodreads.com/book/show/891262.The...
9998,9998,"Waking Up (Healing Hearts, #1)",Renee Dyer,For Adriana Monroe life couldn’t get any bette...,"['New Adult', 'Romance', 'Contemporary Romance...",4.13,263,https://www.goodreads.com/book/show/19347252-w...
9999,9999,Bits and Pieces: Tales and Sonnets,Jas T. Ward,After demands of thousands of fans in various ...,[],5.00,36,https://www.goodreads.com/book/show/21302552-b...

Menghapus kurung di awal dan di akhir data pada kolom Genres

In [59]:
books.Genres = books.Genres.str[1:-1]

In [60]:
print(books.Book[0])
books.Genres[0]

To Kill a Mockingbird

"'Classics', 'Fiction', 'Historical Fiction', 'School', 'Literature', 'Young Adult', 'Historical'"

In [61]:
print(books.Book[2])
books.Genres[2]

Pride and Prejudice

"'Classics', 'Fiction', 'Romance', 'Historical Fiction', 'Literature', 'Historical', 'Audiobook'"

Menampilkan 5 data teratas.

In [62]:
books.head()

,Unnamed: 0,Book,Author,Description,Genres,Avg_Rating,Num_Ratings,URL
0,0,To Kill a Mockingbird,Harper Lee,The unforgettable novel of a childhood in a sl...,"'Classics', 'Fiction', 'Historical Fiction', '...",4.27,"5,691,311",https://www.goodreads.com/book/show/2657.To_Ki...
1,1,Harry Potter and the Philosopher’s Stone (Harr...,J.K. Rowling,Harry Potter thinks he is an ordinary boy - un...,"'Fantasy', 'Fiction', 'Young Adult', 'Magic', ...",4.47,"9,278,135",https://www.goodreads.com/book/show/72193.Harr...
2,2,Pride and Prejudice,Jane Austen,"Since its immediate success in 1813, Pride and...","'Classics', 'Fiction', 'Romance', 'Historical ...",4.28,"3,944,155",https://www.goodreads.com/book/show/1885.Pride...
3,3,The Diary of a Young Girl,Anne Frank,Discovered in the attic in which she spent the...,"'Classics', 'Nonfiction', 'History', 'Biograph...",4.18,"3,488,438",https://www.goodreads.com/book/show/48855.The_...
4,4,Animal Farm,George Orwell,Librarian's note: There is an Alternate Cover ...,"'Classics', 'Fiction', 'Dystopia', 'Fantasy', ...",3.98,"3,575,172",https://www.goodreads.com/book/show/170448.Ani...

Menampilkan berapa banyak jenis buku dan genres

In [63]:
print('Banyak buku: ', len(books.Book.unique()))
print('Banyak Genres: ', len(books.Genres.unique()))

Banyak buku:  9871
Banyak Genres:  8043

Menampilkan jenis genres yang berbeda-beda

In [64]:
print('Jenis Genres: ', books.Genres.unique())

Jenis Genres:  ["'Classics', 'Fiction', 'Historical Fiction', 'School', 'Literature', 'Young Adult', 'Historical'"
 "'Fantasy', 'Fiction', 'Young Adult', 'Magic', 'Childrens', 'Middle Grade', 'Classics'"
 "'Classics', 'Fiction', 'Romance', 'Historical Fiction', 'Literature', 'Historical', 'Audiobook'"
 ...
 "'Dystopia', 'Science Fiction', 'Post Apocalyptic', 'Paranormal', 'Fantasy'"
 "'Fiction', 'Horror', 'Dystopia', 'Coming Of Age'"
 "'New Adult', 'Romance', 'Contemporary Romance', 'Contemporary'"]

Menampilkan info singkat pada data

In [65]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   10000 non-null  int64
 1   Book         10000 non-null  object
 2   Author       10000 non-null  object
 3   Description  9923 non-null   object
 4   Genres       10000 non-null  object
 5   Avg_Rating   10000 non-null  float64
 6   Num_Ratings  10000 non-null  object
 7   URL          10000 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 625.1+ KB

Menampilkan ringkasan nilai pada data, yang menjadi titik fokus pada nilai min dan max

In [66]:
books.Avg_Rating.describe()

count    10000.000000
mean         4.068577
std          0.335359
min          0.000000
25%          3.880000
50%          4.080000
75%          4.260000
max          5.000000
Name: Avg_Rating, dtype: float64

Mengecek berapa banyak nilai null pada data

In [67]:
books.isnull().sum()

Unnamed: 0      0
Book            0
Author          0
Description    77
Genres          0
Avg_Rating      0
Num_Ratings     0
URL             0
dtype: int64

Membuat dataset baru berdasarkan kolom data yang ingin digunakan

In [68]:
new_book = books[['Author','Book','Genres','Avg_Rating']]
new_book

,Author,Book,Genres,Avg_Rating
0,Harper Lee,To Kill a Mockingbird,"'Classics', 'Fiction', 'Historical Fiction', '...",4.27
1,J.K. Rowling,Harry Potter and the Philosopher’s Stone (Harr...,"'Fantasy', 'Fiction', 'Young Adult', 'Magic', ...",4.47
2,Jane Austen,Pride and Prejudice,"'Classics', 'Fiction', 'Romance', 'Historical ...",4.28
3,Anne Frank,The Diary of a Young Girl,"'Classics', 'Nonfiction', 'History', 'Biograph...",4.18
4,George Orwell,Animal Farm,"'Classics', 'Fiction', 'Dystopia', 'Fantasy', ...",3.98
...,...,...,...,...
9995,Ashley Quigley,"Breeders (Breeders Trilogy, #1)","'Dystopia', 'Science Fiction', 'Post Apocalypt...",3.44
9996,Eleanor Gustafson,Dynamo,,4.23
9997,Sam Taylor,The Republic of Trees,"'Fiction', 'Horror', 'Dystopia', 'Coming Of Age'",3.29
9998,Renee Dyer,"Waking Up (Healing Hearts, #1)","'New Adult', 'Romance', 'Contemporary Romance'...",4.13
9999,Jas T. Ward,Bits and Pieces: Tales and Sonnets,,5.00

Melakukan teknik TF-IDF untuk rekayasa fitur teks

In [69]:
data = new_book
data.sample(5)

from sklearn.feature_extraction.text import TfidfVectorizer

# Inisialisasi TfidfVectorizer
tf = TfidfVectorizer()

# Melakukan perhitungan idf pada data genres
tf.fit(data['Genres'])

# Mapping array dari fitur index integer ke fitur nama
tf.get_feature_names_out()

array(['12th', '15th', '16th', '17th', '18th', '19th', '20th', '21st',
       'about', 'abuse', 'academia', 'academic', 'acceptance', 'action',
       'activism', 'adhd', 'adoption', 'adult', 'adventure', 'africa',
       'african', 'age', 'agriculture', 'alchemy', 'algeria', 'aliens',
       'alternate', 'amazon', 'america', 'american', 'americana',
       'americans', 'amish', 'anarchism', 'ancient', 'and', 'angels',
       'animal', 'animals', 'anthologies', 'anthropology', 'anti',
       'apocalyptic', 'archaeology', 'architecture', 'art', 'arthurian',
       'artificial', 'arts', 'asexual', 'asia', 'asian', 'astrology',
       'astronomy', 'atheism', 'audiobook', 'australia', 'authors',
       'autistic', 'autobiography', 'aviation', 'awards', 'bande',
       'banned', 'baseball', 'basketball', 'batman', 'bdsm', 'beast',
       'beauty', 'biblical', 'biography', 'biology', 'birds', 'bizarro',
       'boarding', 'book', 'books', 'botswana', 'brain', 'brazil',
       'british', 'buddhism', 'buisness', 'business', 'canada',
       'canadian', 'care', 'catholic', 'cats', 'century', 'change',
       'chapter', 'chemistry', 'chick', 'childrens', 'china', 'chinese',
       'christian', 'christianity', 'christmas', 'church', 'cities',
       'civil', 'classic', 'classical', 'classics', 'clean', 'climate',
       'club', 'collection', 'collections', 'college', 'comedian',
       'comedy', 'comic', 'comics', 'coming', 'comix', 'communication',
       'computer', 'conspiracy', 'contemporary', 'cookbooks', 'cooking',
       'counselling', 'counter', 'counting', 'cozy', 'crafts', 'crime',
       'criticism', 'cthulhu', 'culinary', 'cults', 'cultural', 'culture',
       'cyberpunk', 'cycling', 'czech', 'danish', 'dark', 'dc', 'death',
       'demons', 'denmark', 'design', 'dessinée', 'detective',
       'development', 'diary', 'diets', 'dinosaurs', 'disability',
       'disorder', 'divination', 'divorce', 'dogs', 'dragonlance',
       'dragons', 'drama', 'drawing', 'drink', 'dungeons', 'dutch',
       'dying', 'dystopia', 'earth', 'ecology', 'economics', 'education',
       'edwardian', 'egypt', 'egyptian', 'elves', 'emotion',
       'engineering', 'english', 'entrepreneurship', 'environment',
       'epic', 'erotic', 'erotica', 'espionage', 'essays', 'ethiopia',
       'eugenics', 'european', 'evolution', 'fae', 'fairies', 'fairy',
       'faith', 'family', 'fan', 'fantasy', 'far', 'fat', 'female',
       'feminism', 'femme', 'fiction', 'fighters', 'figure', 'film',
       'finance', 'finnish', 'fitness', 'flash', 'folk', 'folklore',
       'food', 'foodie', 'football', 'for', 'forgotten', 'fostering',
       'france', 'french', 'futurism', 'futuristic', 'games', 'gaming',
       'gardening', 'gay', 'gender', 'genderfluid', 'genetics',
       'geography', 'geology', 'german', 'germany', 'ghana', 'ghost',
       'ghosts', 'global', 'go', 'god', 'gods', 'gothic', 'government',
       'grade', 'graphic', 'greece', 'greek', 'guidebook', 'halloween',
       'hard', 'harem', 'health', 'help', 'heroic', 'high', 'hinduism',
       'hip', 'historical', 'history', 'hockey', 'holiday', 'holocaust',
       'home', 'homeschool', 'hop', 'horror', 'horse', 'horses', 'how',
       'hugo', 'humor', 'hungarian', 'hungary', 'ii', 'illness', 'in',
       'india', 'indian', 'indonesian', 'inspirational', 'inspired',
       'intelligence', 'international', 'internet', 'iran', 'ireland',
       'irish', 'islam', 'israel', 'issues', 'italian', 'italy', 'japan',
       'japanese', 'jewish', 'josei', 'journal', 'journaling',
       'journalism', 'judaica', 'judaism', 'justice', 'juvenile', 'kenya',
       'kids', 'language', 'latin', 'law', 'lds', 'leadership', 'lebanon',
       'legal', 'leone', 'lesbian', 'lgbt', 'liberia', 'light',
       'linguistics', 'lit', 'literary', 'literature', 'living', 'logic',
       'love', 'lovecraftian', 'magic', 'magical', 'malawi', 'management',
       'manga', 'marathi', 'maritime', 'marriage', 'martial',
       'mathematics', 'mauritius', 'media', 'medical', 'medicine',
       'medieval', 'memoir', 'menage', 'mental', 'mermaids',
       'metaphysics', 'microhistory', 'middle', 'military', 'modern',
       'money', 'monsters', 'morocco', 'mountaineering', 'murder',
       'music', 'musicals', 'musicians', 'mystery', 'mysticism',
       'mythology', 'mythos', 'native', 'natural', 'nature', 'naval',
       'neuroscience', 'new', 'nigeria', 'nobel', 'noir', 'non',
       'nonfiction', 'nordic', 'novel', 'novella', 'novels', 'nursery',
       'nutrition', 'occult', 'of', 'opera', 'outdoors', 'own',
       'paganism', 'pakistan', 'palaeontology', 'paranormal', 'parenting',
       'period', 'personal', 'philosophy', 'photography', 'physics',
       'picture', 'pirates', 'planet', 'planning', 'plantagenet', 'plays',
       'poetry', 'poland', 'police', 'polish', 'political', 'politics',
       'polyamory', 'polygamy', 'pop', 'popular', 'portugal',
       'portuguese', 'post', 'poverty', 'prayer', 'prehistoric',
       'prehistory', 'presidents', 'princesses', 'prize', 'productivity',
       'programming', 'prostitution', 'psychiatry', 'psychoanalysis',
       'psychological', 'psychology', 'pulp', 'punk', 'queer', 'rabbits',
       'race', 'racing', 'racist', 'read', 'readers', 'realism',
       'realistic', 'realms', 'reference', 'regency', 'relations',
       'relationships', 'religion', 'research', 'retellings', 'reverse',
       'revolution', 'revolutionary', 'rhymes', 'right', 'robots', 'rock',
       'roll', 'roman', 'romance', 'romania', 'romanian', 'romantic',
       'romanticism', 'russia', 'russian', 'rwanda', 'satanism',
       'scandinavian', 'school', 'science', 'scotland', 'seinen', 'self',
       'serbian', 'sexuality', 'shapeshifters', 'shojo', 'short',
       'sierra', 'singularity', 'skating', 'skepticism', 'soccer',
       'social', 'society', 'sociology', 'software', 'somalia', 'sorcery',
       'south', 'southern', 'space', 'spain', 'spanish', 'spectrum',
       'speculative', 'spirituality', 'splatterpunk', 'sports', 'spy',
       'star', 'states', 'steampunk', 'stories', 'story', 'storytime',
       'street', 'strips', 'studies', 'sudan', 'superheroes', 'superman',
       'supernatural', 'surreal', 'survival', 'suspense',
       'sustainability', 'sweden', 'swedish', 'sword', 'tale', 'tales',
       'taoism', 'tarot', 'tasmania', 'tea', 'teaching', 'technical',
       'technology', 'teen', 'terrorism', 'textbooks', 'the', 'theatre',
       'thelema', 'theology', 'theories', 'theory', 'thriller', 'tie',
       'time', 'to', 'tragedy', 'trains', 'transgender', 'transport',
       'travel', 'travelogue', 'trek', 'true', 'tudor', 'turkish', 'tv',
       'ukraine', 'ukrainian', 'unfinished', 'unicorns', 'united',
       'universe', 'urban', 'urbanism', 'us', 'utopia', 'vampires',
       'vegan', 'vegetarian', 'victorian', 'video', 'war', 'warming',
       'wars', 'weird', 'werewolves', 'west', 'westerns', 'wicca',
       'wildlife', 'witchcraft', 'witches', 'wolves', 'womens', 'work',
       'world', 'writing', 'york', 'young', 'zen', 'zimbabwe', 'zombies'],
      dtype=object)

Melakukan fit transform agar nilai vektor menjadi matrix lalu menampilkan banyak baris dan kolomnya.

In [70]:
# Melakukan fit lalu ditransformasikan ke bentuk matrix
tfidf_matrix = tf.fit_transform(data['Genres'])

# Melihat ukuran matrix tfidf
tfidf_matrix.shape

(10000, 583)

Mengubah vektor tf-idf dalam bentuk matriks

In [71]:
# Mengubah vektor tf-idf dalam bentuk matriks dengan fungsi todense()
tfidf_matrix.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

Membuat dataframe baru untuk menampikan nilai berdasarkan judul buku dengan genrenya

In [72]:
# Membuat dataframe untuk melihat tf-idf matrix
# Kolom diisi dengan jenis masakan
# Baris diisi dengan nama resto

pd.DataFrame(
    tfidf_matrix.todense(),
    columns=tf.get_feature_names_out(),
    index=data.Book
).sample(22, axis=1).sample(10, axis=0)

,books,regency,football,stories,technology,home,biography,divorce,health,care,...,nonfiction,alternate,cycling,bande,drawing,christmas,comics,vampires,medicine,own
Book,,,,,,,,,,,,,,,,,,,,,
Secrets of Jewish Wealth Revealed!,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.209106,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen Shorts,0.389232,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lysistrata,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Diana Chronicles,0.000000,0.0,0.0,0.0,0.0,0.0,0.572213,0.0,0.0,0.0,...,0.194280,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Beat to Quarters,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Gidget (Gidget series, #1)",0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Made to Stick: Why Some Ideas Survive and Others Die,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.180107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Hidden Hills,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"An Ember in the Ashes (An Ember in the Ashes, #1)",0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Philosophy of Andy Warhol,0.000000,0.0,0.0,0.0,0.0,0.0,0.248111,0.0,0.0,0.0,...,0.168480,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Menampilkan derajat kesamaan antara buku dengan buku lainnya.

In [73]:
from sklearn.metrics.pairwise import cosine_similarity

# Menghitung cosine similarity pada matrix tf-idf
cosine_sim = cosine_similarity(tfidf_matrix)
cosine_sim

array([[1.        , 0.271285  , 0.6787677 , ..., 0.04292223, 0.06640811,
        0.        ],
       [0.271285  , 1.        , 0.13194833, ..., 0.02070199, 0.06405912,
        0.        ],
       [0.6787677 , 0.13194833, 1.        , ..., 0.04800123, 0.19249784,
        0.        ],
       ...,
       [0.04292223, 0.02070199, 0.04800123, ..., 1.        , 0.        ,
        0.        ],
       [0.06640811, 0.06405912, 0.19249784, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

Menampikan derajat kesamaan antar buku

In [74]:
# Membuat dataframe dari variabel cosine_sim dengan baris dan kolom berupa judul buku
cosine_sim_df = pd.DataFrame(cosine_sim, index=data['Book'], columns=data['Book'])
print('Shape:', cosine_sim_df.shape)

# Melihat similarity matrix pada setiap resto
cosine_sim_df.sample(10, axis=1).sample(10, axis=0)

Shape: (10000, 10000)

Book,Tutunamayanlar,Free Will [Deckle Edge],"Theory of People: Understanding Behaviors, Business, Economics, Feelings, and the Mind","Queen of Shadows (Throne of Glass, #4)",Monique,Franz Kafka's The Castle,The Bridge Across Forever: A True Love Story,"The Heir (The Selection, #4)","The Crow Trap (Vera Stanhope, #1)",Mister Pip
Book,,,,,,,,,,
Edie: American Girl,0.000000,0.027186,0.030330,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
Nikola Tesla: Imagination and the Man That Invented the 20th Century,0.000000,0.103252,0.320766,0.000000,0.0,0.000000,0.000000,0.089522,0.000000,0.132364
The Pacific Depths,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
Lost Illusions,0.221535,0.000000,0.000000,0.014810,0.0,0.376119,0.094871,0.042331,0.126645,0.052411
The Unremembered Girl,0.011981,0.000000,0.000000,0.109365,0.0,0.015432,0.021863,0.115172,0.631160,0.115437
There Will Be Lies,0.012542,0.000000,0.000000,0.338554,0.0,0.016154,0.083512,0.280675,0.340174,0.279638
"Kergulen (Kergulen, #1)",0.044538,0.000000,0.000000,0.404354,0.0,0.057366,0.296572,0.426566,0.069852,0.227195
The Half Brother,0.227872,0.000000,0.000000,0.047423,0.0,0.390396,0.141284,0.135549,0.169576,0.505984
Beyond Nostalgia,0.015783,0.000000,0.000000,0.101365,0.0,0.020329,0.128318,0.177379,0.024754,0.185135
Proof of Heaven: A Neurosurgeon's Journey into the Afterlife,0.000000,0.254187,0.130109,0.000000,0.0,0.000000,0.192066,0.101116,0.000000,0.000000

In [75]:
def book_recommendations(judul_buku, similarity_data=cosine_sim_df, items=data[['Book', 'Genres']], k=10):
    """
    Rekomendasi Buku berdasarkan kemiripan dataframe

    Parameter:
    ---
    book : tipe data string (str)
                Judul Buku (index kemiripan dataframe)
    similarity_data : tipe data pd.DataFrame (object)
                      Kesamaan dataframe, simetrik, dengan buku sebagai
                      indeks dan kolom
    items : tipe data pd.DataFrame (object)
            Mengandung kedua nama dan fitur lainnya yang digunakan untuk mendefinisikan kemiripan
    k : tipe data integer (int)
        Banyaknya jumlah rekomendasi yang diberikan
    ---


    Pada index ini, kita mengambil k dengan nilai similarity terbesar
    pada index matrix yang diberikan (i).
    """


    # Mengambil data dengan menggunakan argpartition untuk melakukan partisi secara tidak langsung sepanjang sumbu yang diberikan
    # Dataframe diubah menjadi numpy
    # Range(start, stop, step)
    index = similarity_data.loc[:,judul_buku].to_numpy().argpartition(
        range(-1, -k, -1))

    # Mengambil data dengan similarity terbesar dari index yang ada
    closest = similarity_data.columns[index[-1:-(k+2):-1]]

    # Drop judul buku agar judul buku yang dicari tidak muncul dalam daftar rekomendasi
    closest = closest.drop(judul_buku, errors='ignore')

    return pd.DataFrame(closest).merge(items).head(k)

Menampilkan buku yang akan menjadi dasar untuk mendapatkan rekomendasi pada buku lain.

In [76]:
data[data.Book.eq('Train Dreams')]

,Author,Book,Genres,Avg_Rating
1472,Denis Johnson,Train Dreams,"'Fiction', 'Historical Fiction', 'Novella', 'W...",3.9

Menampikan rekomendasi buku berdasarkan model yang telah didapatkan sebelumnya

In [77]:
# Mendapatkan rekomendasi buku
book_recommendations('Train Dreams')

,Book,Genres
0,"Love Medicine (Love Medicine, #1)","'Fiction', 'Historical Fiction', 'Short Storie..."
1,"All the Pretty Horses (The Border Trilogy, #1)","'Fiction', 'Westerns', 'Historical Fiction', '..."
2,Angle of Repose,"'Fiction', 'Historical Fiction', 'Classics', '..."
3,Legends of the Fall,"'Fiction', 'Historical Fiction', 'Westerns', '..."
4,Lost Nation,"'Historical Fiction', 'Fiction', 'Historical',..."
5,The Sense of Touch,"'Short Stories', 'Literary Fiction', 'Fiction'..."
6,Little Century,"'Historical Fiction', 'Fiction', 'Westerns', '..."
7,The Nightingales of Troy: Connected Stories,"'Short Stories', 'Fiction', 'Historical Fictio..."
8,Point Omega,"'Fiction', 'Novels', 'American', 'Literature',..."
9,Memory Wall,"'Short Stories', 'Fiction', 'Contemporary', 'H..."